"""Expanded short-text corpus for FSOT distill (no external download required)."""

PROBES = [
    "The capital of France is",
    "def fibonacci(n):",
    "In mathematics, the derivative of x^2 is",
    "Once upon a time",
    "2 + 2 =",
    "The largest planet in our solar system is",
    "print('hello",
    "Water freezes at",
]

# Diverse short prefixes for KL distillation
TRAIN_BASE = PROBES + [
    "Python is a programming language that",
    "The speed of light is approximately",
    "To sort a list in reverse order",
    "Photosynthesis converts",
    "The mitochondria is",
    "In computer science, a binary tree",
    "Newton's second law states",
    "The chemical formula for water is",
    "Hello, my name is",
    "The president of the United States",
    "1 + 1 =",
    "for i in range(",
    "def main():",
    "import numpy as",
    "The square root of 9 is",
    "Gravity on Earth is",
    "The boiling point of water is",
    "In geometry, a triangle has",
    "Machine learning models learn from",
    "The HTTP status code for OK is",
    "Photosynthesis requires sunlight and",
    "The CPU stands for",
    "A linked list stores",
    "The function f(x)=x^2 is",
    "In history, the Roman Empire",
    "The Amazon rainforest is located in",
    "DNA stands for",
    "An algorithm is a step-by-step",
    "The first element of a Python list is",
    "Climate change is caused by",
    "The unit of force is the",
    "A prime number is divisible by",
    "Git is used for",
    "The Moon orbits the",
    "In economics, supply and demand",
    "A compiler translates",
    "The human heart has how many chambers",
    "JSON stands for",
    "The integral of 1 is",
    "Open source software is",
    "The Pacific Ocean is the",
    "Recursive functions call",
    "A variable stores a",
    "The chemical symbol for gold is",
    "Earth completes one orbit in",
    "SQL is used to query",
    "The smallest prime number is",
    "A neural network consists of",
    "The capital of Japan is",
    "In physics, energy is conserved",
    "A stack uses last-in",
    "The color of the sky is often",
    "Markdown is used to format",
    "The speed of sound in air is",
    "A dictionary maps keys to",
    "Photosynthesis produces oxygen and",
    "The number of bits in a byte is",
    "An API allows software to",
    "The largest mammal is the",
    "In algebra, solve for x in",
    "A GPU accelerates",
    "The first law of thermodynamics",
    "Regex is used for",
    "The currency of the European Union is",
    "A queue uses first-in",
    "Hydrogen has atomic number",
    "The center of our solar system is",
    "Unit testing checks that",
    "The derivative of sin(x) is",
    "Linux is an operating",
    "A black hole has strong",
    "In Python, len(list) returns",
    "The chemical formula for salt is",
    "An IDE helps developers",
    "The speed of light in vacuum is",
    "A hashmap provides average",
    "Carbon dioxide is written as",
    "The Earth is approximately",
    "Floating point numbers can",
    "A semiconductor is used in",
    "The Fibonacci sequence starts",
    "Object-oriented programming uses",
    "The Atlantic Ocean separates",
    "A tensor is a multi-dimensional",
    "The boiling point of water in Celsius is",
    "Recursion needs a base",
    "The Sun is a type of",
    "Binary search runs in",
    "The noble gas helium is",
    "A packet on a network",
    "The quadratic formula solves",
    "Machine learning needs training",
    "The largest desert on Earth is",
    "In Git, git commit creates",
    "A boolean value is either",
    "The force of gravity depends on",
    "HTTP is a protocol for",
    "The element with symbol Fe is",
    "A process in an OS",
    "The area of a circle is",
    "Vector databases store",
    "The capital of Italy is",
    "An exception in Python is",
    "The wavelength of red light is",
    "A socket connects two",
    "The number pi is approximately",
    "Parallel computing uses multiple",
    "The human body temperature is about",
    "A middleware sits between",
    "The speed of a free-falling object",
    "Unicode encodes text as",
    "A battery stores",
    "The first computer bug was",
    "In statistics, the mean is",
    "A firewall protects",
    "The mass of a proton is",
    "Asynchronous code does not",
    "The capital of Canada is",
    "A cache improves performance by",
    "The chemical formula for ozone is",
    "A virtual machine emulates",
    "The period of a pendulum depends on",
    "REST APIs typically use",
    "The largest continent is",
    "A mutex prevents concurrent",
    "The refractive index of water is",
    "Docker containers package",
    "The entropy of a system",
    "A primary key uniquely",
    "The age of the universe is about",
    "Gradient descent minimizes",
    "The capital of Australia is",
    "A semaphore controls access",
    "The density of water is",
    "TypeScript adds types to",
    "The speed of Earth's rotation",
    "A load balancer distributes",
    "The pH of pure water is",
    "An embedding maps text to",
    "The tallest mountain is",
    "A deadlock occurs when",
    "The charge of an electron is",
    "Kubernetes orchestrates",
    "The melting point of ice is",
    "Attention in transformers computes",
    "The capital of Brazil is",
    "A race condition happens when",
    "The Planck constant relates",
    "A transformer model uses",
    "The volume of a sphere is",
    "Softmax converts scores into",
    "The largest ocean is the",
    "Backpropagation updates",
    "The chemical symbol for sodium is",
    "A GPU has many parallel",
    "The first element of the periodic table is",
]


def train_texts() -> list[str]:
    """Return training prefixes (deduped)."""
    seen = set()
    out = []
    for t in TRAIN_BASE:
        if t not in seen:
            seen.add(t)
            out.append(t)
    return out
